# Generated by Django 4.1 on 2022-09-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mounth', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('pdfReport', models.FileField(blank=True, upload_to='2022-reports')),
            ],
        ),
    ]
