# Generated by Django 4.1 on 2022-08-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('adress', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('born', models.DateField(default=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('number', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True)),
                ('genre', models.CharField(blank=True, choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], max_length=1, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_baptized_water', models.BooleanField(default=False)),
                ('is_baptized_holySpirit', models.BooleanField(default=False)),
                ('is_tither', models.BooleanField(default=False)),
                ('upload', models.FileField(blank=True, upload_to='uploads/')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.church')),
            ],
        ),
    ]
