# Generated by Django 4.1 on 2022-08-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
