# Generated by Django 4.1 on 2022-08-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
