# Generated by Django 4.1 on 2022-09-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrie', '0002_entrie_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrie',
            name='category',
            field=models.CharField(choices=[('Oferta', 'ofert'), ('Dízimo', 'Dizim')], max_length=8),
        ),
    ]
