# Generated by Django 4.1 on 2022-09-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrie', '0003_alter_entrie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrie',
            name='category',
            field=models.CharField(choices=[('oferta', 'Oferta'), ('dizimo', 'Dízimo')], max_length=8),
        ),
        migrations.AlterField(
            model_name='entrie',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
