# Generated by Django 4.1 on 2022-09-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrie', '0004_alter_entrie_category_alter_entrie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrie',
            name='ocassion',
            field=models.CharField(max_length=55),
        ),
    ]
